- 3]. Competitive Programming/HackerRank/Java/introduction/JavaCurrencyFormatter.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaDatatypes.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaDateAndTime.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaEndOfFile.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaIfElse.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaIntToString.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaLoopsI.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaLoopsII.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaOutputFormatting.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaStaticInitializerBlock.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaStdinAndStdoutI.java
- 3]. Competitive Programming/HackerRank/Java/introduction/JavaStdinAndStdoutII.java
- 3]. Competitive Programming/HackerRank/Java/introduction/WelcomeToJava.java
Welcome to Java!--------> WelcomeToJava.java 
Java Stdin and Stdout I--------> JavaStdinAndStdoutI.java 
Java If-Else--------> JavaIfElse.java 
Java Stdin and Stdout II--------> JavaStdinAndStdoutII.java 
Java Output Formatting--------> JavaOutputFormatting.java 
Java Loops I--------> JavaLoopsI.java 
Java Loops II--------> JavaLoopsII.java 
Java Datatypes--------> JavaDatatypes.java 
Java End-of-file--------> JavaEndOfFile.java 
Java Static Initializer Block--------> JavaStaticInitializerBlock.java 
Java Int to String--------> JavaIntToString.java 
Java Date and Time--------> JavaDateAndTime.java 
Java Currency Formatter--------> JavaCurrencyFormatter.java
> Solution of hackerrank Introduction 

- 3]. Competitive Programming/LeetCode/Problems/_0051)_N-Queens.java
Problem Description :
https://leetcode.com/problems/n-queens/
> Added Solution for NQueens Problem no 51 from Leetcode

- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/BELLA_CIAO.cpp
- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/BITWISE_TUPLES.cpp
- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/MINIMUM_DUAL_AREA.cpp
- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/MINIMUM_SUBTREE_COVER.cpp
- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/SHORTEST_ROUTE.cpp
- 3]. Competitive Programming/CodeChef/JUNE_LONG_CHALLENGE_DIV_3/SUMMER_HEAT.cpp
Hello @AkashSingh3031 ,
Kindly Review this PR !
> ADDED CODECHEF JUNE LONG CHALLNEGE DIV 3 SOLUTION IN C++

- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/ISS.cpp
- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/MODEQ.cpp
- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/TCTCTOE.cpp
- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/THOUSES.cpp
- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/VPATH.cpp
- 3]. Competitive Programming/CodeChef/May Long Challenge 2021/XOREQUAL.cpp
Solutions of May long challenge 2021 in CPP
> Added May Long Challenge 2021 to 3]. Competitive Programming/CodeChef

- 1]. DSA/450 DSA by ( Love Babbar Bhaiya )/C++/01]. Array/_06) Union_of_two_arrays.cpp
Added the code for union of arrays in array of Love Babbar DSA sheet. This is my first contribution.
> Added union of arrays in array

- 2]. Technical Subjects/Interview Questions/2). Database Management System (DBMS)/_01)Top_50_DBMS_Question_and_answers.md
@AkashSingh3031 : This is the **Top 50 DBMS interview questions**
> Top 50 DBMS interview questions

- 3]. Competitive Programming/LeetCode/Problems/Java/_0046)_Permutations.java
Permutations : 
https://leetcode.com/problems/permutations/
> Leet code Solution to problem no 46

- 1]. DSA/1]. Data Structures/03]. Recursion/C++/_8)_Rat In A Maze.cpp
Another popular recursion+backtracking interview question. Please look into it.
> Create _8)_Rat In A Maze.cpp

- 1]. DSA/1]. Data Structures/09]. Stack/C++/_1)_The Stock Span Problem.cpp
> Create _1)_The Stock Span Problem.cpp

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_1)_Minimum Steps to reach the end.cpp
Popular interview question on dynamic programming. Please look into it.
> Create _1)_Minimum Steps to reach the end.cpp

- 6]. Important Books/Important_Books_Link.md
I have added a important book  "Data structure and Algorithm in Python" in the 6]. Important Books section.
> Added a Important Book

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_2)_.Frog Jump-1.cpp
A very good problem to understand dynamic programming. Included the problem statement and some test cases as well.
> Create _2)_.Frog Jump-1.cpp

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_3)_Number of Coins.cpp
Popular Dynamic programing question
> Created _3)_Number of Coins.cpp

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_4)_Wines Problem Top Down dp.cpp
Popular dynamic programming question
> Create _4)_Wines Problem Top Down dp.cpp

- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/C++/_1)_Merge Sort On 2 Linked Lists.cpp
> Create _1)_Merge Sort On 2 Linked Lists.cpp

- 1]. DSA/2]. Algorithms/09]. Backtracking/C++/_1)_Sudoku Solver.cpp
> Create _1)_Sudoku Solver.cpp

- 3]. Competitive Programming/LeetCode/Problems/C++/0008)string_to_int_atoi.cpp
- 3]. Competitive Programming/LeetCode/Problems/C++/0128) Longest_consecutive_subsequence.cpp
- 3]. Competitive Programming/LeetCode/Problems/Python/0002)Add_two_numbers.py
- 3]. Competitive Programming/LeetCode/Problems/Python/0005)Longest_palindromic_substring.py
- 3]. Competitive Programming/LeetCode/Problems/Python/0009)PalindromeNumber.py
- 3]. Competitive Programming/LeetCode/Problems/Python/0012)Int_to_Roman.py
- 3]. Competitive Programming/LeetCode/Problems/Python/0013)Roman_to_int.py
- 3]. Competitive Programming/LeetCode/Problems/Python/0014)Longest_common_prefix.py
standard solutions dont have comments but any of my solution  which I think might be hard to understand should have comments
> added some leetcode solutions in py and cpp

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_5)_Ladders Problem Bottom up dp.cpp
Popular dynamic programing question
> Created _5)_Ladders Problem Bottom up dp.cpp

- 1]. DSA/2]. Algorithms/07]. Dynamic Programming/C++/_6)_Box Stacking Problem.cpp
Very important 1D DP Question. Added a Test Case and explanation of the code.
> Create _6)_Box Stacking Problem.cpp

- 1]. DSA/2]. Algorithms/06]. Greedy/Java/DijkstraAlgorithm.java
- 1]. DSA/2]. Algorithms/06]. Greedy/Java/PrimsAlgorithm.java
> added Dijstra and Prims Algorithm for Java

- 3]. Competitive Programming/LeetCode/Problems/Java/_0399)_EvaluateDivision.java
Solution to Leetcode Problem no : 399
https://leetcode.com/problems/evaluate-division/
> Solution to Leetcode Problem no : 399

- 6]. Important Books and Resources/Computer Science Prep.md
I have added curated list of free courses from reputable universities like MIT, Stanford, and Princeton.
> Created Computer Science Prep.md

- 1]. DSA/1]. Data Structures/03]. Recursion/C++/_9)_Distinct Occurences.cpp
> Create _9)_Distinct Occurences.cpp

- 1]. DSA/2]. Algorithms/08]. Divide and Counqer/Java/resources/MergeSort.md
- 1]. DSA/2]. Algorithms/08]. Divide and Counqer/Java/resources/QuickSort.md
@AkashSingh3031 . Please Checkout
> Added QuickSort and Some other Codes..

- 7.] Behavioural Interview/behavioural-interview-ques.md
- README.md
- 
- Complete FAANG preparation is incomplete without Behavioural interview questions. I bet many candidates are facing a similar problem of resources for good cultural fit or behavioral interview questions.
- (prefer animated gif)
- Issue Number: N/A
> Behavioural interview Prep

- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Bash/Day_0_Hello_World.sh
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Bash/Day_3_Intro_to_Conditional_Statements.sh
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Scala/Day_0_Hello_World.scala
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Scala/Day_1_Data_Types.scala
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Scala/Day_2_Operators.scala
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Scala/Day_3_Intro_to_Conditional_Statements.scala
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/08]. 30 Days of Code/Scala/Day_4_Class_vs_Instance.scala
Soumen
- NA
- Issue Number: #NA
- Adding solutions in another programming language (Bash & Scala)
- NA
> Adding Scala and Bash solutions for 30 Days of Code

- 1]. DSA/4]. Striver Series/30 Days of SDE Sheet/C++/Day-02 (Arrays)/1].Set matrix zeroes.cpp
> Create 1].Set matrix zeroes.cpp

- 1]. DSA/4]. Striver Series/30 Days of SDE Sheet/C++/Day-02 (Arrays)/3].Next permutation.cpp
> Create 3].Next permutation.cpp

- 1]. DSA/4]. Striver Series/30 Days of SDE Sheet/C++/Day-02 (Arrays)/2].Pascal's Triangle.cpp
> Create 2].Pascal's Triangle.cpp

- 1]. DSA/1]. Data Structures/01]. Array/Python/_001)_Search_Element.py
- 1]. DSA/1]. Data Structures/01]. Array/Python/_002)_Insert_Element.py
- 
Added Array_Search and Array_Insert in python
> Harish3124

- 1]. DSA/4]. Striver Series/30 Days of SDE Sheet/C++/Day-02 (Arrays)/6].Rotate matrix.cpp
> Create 6].Rotate matrix.cpp

- 1]. DSA/1]. Data Structures/06]. Linked List/Python/addition.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/compare_strings.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/deletion.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/insertion.py
- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Bubble_Sort.py
- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Insertion_Sort.py
- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Merge_Sort.py
- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Selection_Sort.py
- 1]. DSA/2]. Algorithms/09]. Backtracking/Python/N-Queens.py
- 1]. DSA/2]. Algorithms/09]. Backtracking/Python/Rat_maze.py
- 1]. DSA/2]. Algorithms/09]. Backtracking/Python/sudoku.py
> Added some Sorting algos and and three main Backtracking algos with PYTHON

- 1]. DSA/1]. Data Structures/06]. Linked List/Python/Rotate_LinkedList.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/count_rotations.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/insert_whole_LL_at_k.py
- 1]. DSA/1]. Data Structures/06]. Linked List/Python/swap_nodes.py
> Adding some important LinkedList Algorithms

- 1]. DSA/1]. Data Structures/08]. Circular Linked List/Python/check_circular_linkedlist.py
> This time circular linked list Happy Coding :)

- 1]. DSA/1]. Data Structures/16]. Trie/Python/Insert_search_&_delete.py
I did all basic operations of trie in one script(Python)
- 
> Insertion Searching and Deletion of Nodes

- 1]. DSA/1]. Data Structures/01]. Array/C++/_002)_Insert_Element.cpp
> Add comments

- 1]. DSA/2]. Algorithms/06]. Greedy/Python/Dijkstra's Algorithm.py
- 1]. DSA/2]. Algorithms/06]. Greedy/Python/Kruskal’s Minimum Spanning Tree Algorithm.py
Added  Kruskal's Minimum Tree Algorithm using Union
- Issue Number: #170
> Greedy Algorithm-2

- 1]. DSA/2]. Algorithms/02]. Sorting Algorithms/C++/_2)_Heap_Sort.cpp
Want to contribute my Heap Sort code (C++) to this repository.
> Added the code for Heap Sort

- 1]. DSA/1]. Data Structures/19]. Bit Manipulation/C++/_001)_Find_ith_bit.cpp
- 1]. DSA/1]. Data Structures/19]. Bit Manipulation/C++/_002)_Replace_Bits.cpp
Created a new folder **Bit Manipulation** in Data Structure Section and added codes in C++.
> Added Bit Manipulation Folder with some codes

- 1]. DSA/1]. Data Structures/19]. Bit Manipulation/C++/_003)_Decimal_to_Binary.cpp
Added decimal to binary in Bit Manipulation folder in C++
> Added decimal to binary in Bit Manipulation folder

- 1]. DSA/1]. Data Structures/19]. Bit Manipulation/C++/_004)_Clear_ith_bit.cpp
Added Clear ith bit in Bit Manipulation Folder (C++)
> Added Clear ith bit in Bit Manipulation Folder

- 5]. Projects/Machine Learning & Data Science  (ML-DS)/Python/Deep Learning Projects/Natural Language Processing/1]. Text_Summarization_using_Transformers/README.md
- 5]. Projects/Machine Learning & Data Science  (ML-DS)/Python/Deep Learning Projects/Natural Language Processing/1]. Text_Summarization_using_Transformers/Text_Summarization.ipynb
- [o] YES
- 
-Added Text Summurization
- [o] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [o] I've checked the issue list before deciding what to submit.
- [o] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [o] I've add work in proper folder
- [o] I've not delete/modify previous codes.
> Uploaded Text Summarization Project

- 1]. DSA/1]. Data Structures/01]. Array/Python/_001)_Search_Element.py
Changed starting index to 0 as range(1, len(arr)) will miss to compare
with first element in array.
- 
- Issue Number:  Searching first element in list will return -1 as loop is starting from index 1.
-  Changed starting index to 0 so as to consider first element to compare.
- ![image](https://user-images.githubusercontent.com/4373228/132171696-9e1c838c-8906-4b77-9c58-9d81a2b9a48c.png)
> ++ Changed search starting index to 0

- 1]. DSA/1]. Data Structures/01]. Array/C++/_003)_Delete_Element.cpp
> Added Comment to Code

- 1]. DSA/1]. Data Structures/19]. Bit Manipulation/C++/_005)_If_A_Number_Is_Power_Of_Two.cpp
Added if a number is a power of of 2 (C++) in Bit Manipulation folder.
> Added if a number is a power of 2 or not

- 3]. Competitive Programming/03]. HackerRank/1]. Practice/03]. Python/2)Sets/Introduction_to_sets.py
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/03]. Python/2)Sets/TheCaptains_room.py
- 3]. Competitive Programming/03]. HackerRank/1]. Practice/03]. Python/2)Sets/set.add().py
> 3 solved questions on set added hackerrank

- 1]. DSA/2]. Algorithms/01]. Searching Algorithms/Python/01) Binary Search.py
- 1]. DSA/2]. Algorithms/01]. Searching Algorithms/Python/02) Recursive Binary Search.py
Binary Search and Recursive Binary Search added in Python !
> Binary Search and Recursive Binary Search added in Python !

- 1]. DSA/2]. Algorithms/01]. Searching Algorithms/Python/06) Fibonacci Search.py
> Added Fibonacci Search in Python 🐍

- README.md
> Added Simplify Logo

- 1]. DSA/1]. Data Structures/01]. Array/Python/_006)_Left_Rotate_Array_by_d_places.py
- 
- corrected the explanation in the comments
> corrected the explanation in the comments

- 1]. DSA/3]. 450 DSA by ( Love Babbar Bhaiya )/C++/13]. Trie/_01)_Construct_a_trie_from_scratch.cpp
- [*] YES
- 
- [ * ] 𝑫𝑺𝑨
- 
- [*] I've checked the issue list before deciding what to submit.
- [*] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [*] I've add work in proper folder
- [*] I've not delete/modify previous codes.
> Add LeetCode +450 DSA Sheet solution - Trie

- 1]. DSA/3]. 450 DSA by ( Love Babbar Bhaiya )/C++/13]. Trie/_03)_Word_Break_Problem_(Trie solution).cpp
- [* ] YES
- 
- [* ] 𝑫𝑺𝑨
- Add LeetCode +450 DSA Sheet solution - Trie(Q-3)
- 
- [ *] I've checked the issue list before deciding what to submit.
- [ *] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ *] I've add work in proper folder
- [ *] I've not delete/modify previous codes.
> Add LeetCode +450 DSA Sheet solution - Trie(Q-3)

- 1]. DSA/3]. 450 DSA by ( Love Babbar Bhaiya )/C++/14]. Dynamic Programming/_07)_Edit_Distance.cpp
- [* ] YES
- 
- [* ] 𝑫𝑺𝑨
- Add LeetCode +450 DSA Sheet solution - DP(Q-7)
- [ *] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [* ] I've checked the issue list before deciding what to submit.
- [ *] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ *] I've add work in proper folder
- [ *] I've not delete/modify previous codes.
> Add LeetCode +450 DSA Sheet solution - DP(Q-7)

- 1]. DSA/3]. 450 DSA by ( Love Babbar Bhaiya )/C++/14]. Dynamic Programming/_14)_Longest_Common_Subsequence.cpp
- [* ] YES
- 
- [ *] 𝑫𝑺𝑨
- [ *] I've checked the issue list before deciding what to submit.
- [ *] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ *] I've add work in proper folder
- [* ] I've not delete/modify previous codes.
> Add LeetCode +450 DSA Sheet solution - DP(Q-14)

- 3]. Competitive Programming/06]. CodeChef/2]. Compete/2]. Cook-off/Div 2/January 2022/Mean Maximization.cpp
- 3]. Competitive Programming/06]. CodeChef/2]. Compete/2]. Cook-off/Div 2/January 2022/Palindromes Not Allowed.cpp
- 3]. Competitive Programming/06]. CodeChef/2]. Compete/2]. Cook-off/Div 2/January 2022/Subsegment Divisibility.cpp
- [ *] YES
- 
- [ *] 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
- [ *] I've checked the issue list before deciding what to submit.
- [ *] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [* ] I've add work in proper folder
- [ *] I've not delete/modify previous codes.
> Added January 2022 Cook-Off

- 3]. Competitive Programming/06]. CodeChef/2]. Compete/3]. Lunch Time/Div 2/January Lunchtime 2022/Prefix Zeros.cpp
- 3]. Competitive Programming/06]. CodeChef/2]. Compete/3]. Lunch Time/Div 2/January Lunchtime 2022/Subarray Permutations.cpp
- [ *] YES
- 
- [* ] 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
-
- [ *] I've checked the issue list before deciding what to submit.
- [* ] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ *] I've add work in proper folder
- [ *] I've not delete/modify previous codes.
> Added January Lunchtime 2022

- 1]. DSA/1]. Data Structures/01]. Array/Python/_002)_Insert_Element.py
> Contributing with some caveats about grammar and code

- 1]. DSA/1]. Data Structures/01]. Array/Python/_002)_Insert_Element.py
> Array insertion

- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 1/CCD.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 1/COST_MANIA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 1/DCP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 1/PMA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 2/CCD.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 2/COST_MANIA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 2/DCP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 2/PMA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 2/STRP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/BOMBTHEBASE.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/CCD.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/COST_MANIA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/DCP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/PMA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 3/STRP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/BOMBTHEBASE.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/CCD.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/DCP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/FBC.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/PMA.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/STRP.cpp
- 3]. Competitive Programming/11]. CodeChef/2]. Compete/4]. Starters/29]. Starters-29/Div. 4/TYRE.cpp
- [*] YES
- 
- [*] 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
- (Add Running Work Demo Image)
- [*] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [*] I've checked the issue list before deciding what to submit.
- [*] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [*] I've add work in proper folder
- [*] I've not delete/modify previous codes.
> Added CodeChef Starters 29 Solutions

- 3]. Competitive Programming/Readme.md
> Fix workat.tech practice link

- 1]. DSA/1]. Data Structures/03]. Recursion/Python/factorial.py
> Calculating factorial with recursion

- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Pow(x,n).py
- YES
[The-Complete-FAANG-Preparation](https://github.com/ginny100/The-Complete-FAANG-Preparation)
[ ] 𝑫𝑺𝑨
- I think the existing solution to Pow(x,n) in this repo is the iterative approach.
- I've updated the Pow(x,n).py file to provide the recursive solution.
- I've read the instructions on the README file before submitting my application.
- I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- I've checked the issue list before deciding what to submit.
- I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- I've add work in proper folder
> Update recursive solution for Pow(x,n)

- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Binary_Number.py
- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Count_Digits.py
- YES
- 𝑫𝑺𝑨
- Added 2 new Recursion problems
- <img width="189" alt="Screen Shot 2022-05-19 at 9 51 47 PM" src="https://user-images.githubusercontent.com/58489398/169439285-7c37ef5f-0bd6-4328-94fc-756e67b0774a.png">
- <img width="246" alt="Screen Shot 2022-05-19 at 9 52 01 PM" src="https://user-images.githubusercontent.com/58489398/169439318-75f174d9-0d34-470c-a4cc-aafd323d4fd9.png">
I've read the instructions on the README file before submitting my application.
I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
I've checked the issue list before deciding what to submit.
I've followed [Tree …
> Added Binary_Number.py and Count_Digits.py

- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Search_In_A_Binary_Search_Tree.py
- YES
- 𝑫𝑺𝑨
- Added the leetcode problem Search in a Binary Search Tree
- Updated Add Contents.txt
- I've read the instructions on the README file before submitting my application.
- I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- I've checked the issue list before deciding what to submit.
- I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- I've add work in proper folder
> Added Search in BST

- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Binary_Tree_Traversal_(i).py
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Binary_Tree_Traversal_(ii).py
- YES
- 𝑫𝑺𝑨 + CP
- Added tree traversals iterative approach
- I've read the instructions on the README file before submitting my application.
- I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- I've checked the issue list before deciding what to submit.
- I've followed [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- I've added work in the proper folder
> Add iterative tree traversals

- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Binary_Tree_Level_Order_Traversal_(i).py
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Binary_Tree_Level_Order_Traversal_(ii).py
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Binary_Tree_Level_Order_Traversal_(iii).py
- YES
- 𝑫𝑺𝑨 + CP
- I added the multiple solutions for Binary Tree Level Order Traversal
- I've read the instructions on the README file before submitting my application.
- I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- I've checked the issue list before deciding what to submit.
- I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- I've add work in proper folder
> Added leetcode Binary Tree Level Order Traversal

- 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/A/1657) Integer Moves.cpp
- 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/B/1657) XY Sequence.cpp
- 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/C/1657) Bracket Sequence Deletion.cpp
- YES
- [[]()](https://github.com/zufius/The-Complete-FAANG-Preparation)https://github.com/zufius/The-Complete-FAANG-Preparation
- Add problems A,B,C for contest Codeforces #1657
- Add 3 files:
+ 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/A/1657) Integer Moves.cpp
+ 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/B/1657) XY Sequence.cpp
+ 1]. DSA + CP/2]. Competitive Programming/13]. CodeForces/1]. Problem Set/Levels/C/1657) Bracket Sequence Deletion.cpp
- ![1657C](https://i.imgur.com/5BXUUT5.png)
- ![1657B](https://i.imgur.com/DF44VG6.png)
- ![1657A](https://i.imgur.com/EA9nWdt.png)
> Problems A,B,C contest Codeforces #1657

- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Symmetric_Tree_(i).py
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Symmetric_Tree_(ii).py
- Added the Symmetric Tree leetcode problem
> Added Symmetric Tree

- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/12]. Tree/Python/Path_Sum.py
- I've added the leetcode problem Path Sum
> Added Path Sum

- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/03]. Recursion/Python/Symmetric_Tree.py
- I added the Leetcode problem Symmetric Tree to the Recursion folder.
> Added Symmetric Tree to Recursion folder

- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/Python/Add Contents.txt
- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/Python/Validate_Binary_Search_Tree.py
- I've added the leetcode problem "Validate Binary Search Tree"
> Added Validate BST leetcode problem

- 1]. DSA + CP/1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Java/BubbleSort.java
- [https://github.com/edo-ce/The-Complete-FAANG-Preparation.git]()
- Add bubbleSort to java sorting algorithms
- ![java_bubble_sort_demo](https://user-images.githubusercontent.com/72577095/180258028-1782869a-c1bc-42e3-bd66-36773e680469.png)
> Add BubbleSort to java sorting algorithms

- 1]. DSA + CP/1]. DSA/2]. Algorithms/02]. Sorting Algorithms/Java/SelectionSort.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_01)_Java_Strings_Introduction.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_02)_Java_Substring.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_03)_Java_Substring_Comparisons.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_04)_Java_String_Reverse.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_05)_Java_Anagrams.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_06)_Java_String_Tokens.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_07)_Pattern_Syntax_Checker.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/2]. Strings/_08)_Java_Regex.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/6]. Exception Handling/_01)_Java_Exception_Handling_TryCatch.java
- 1]. DSA + CP/2]. Competitive Programming/10]. HackerRank/1]. Practice/04]. Java/6]. Exception Handling/_02)_Java_Exception_Handling.java
- [https://github.com/edo-ce/The-Complete-FAANG-Preparation.git]()
- Add selection sort algorithm to java sorting algorithms, HackerRank java strings solutions and HackerRanck java error handling solutions. The HackerRanck solutions have passed all test cases.
-
> Add Java Strings and Error Handling HackerRank solutions and java SelectionSort

- 5]. Important Books and Resources/Important_Books_Link.md
- [ ✓ ] YES
- []()
- [ ✓ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- Added a new book for coding interviews
- (Add Running Work Demo Image)
- [ ✓ ] I've read the instructions on the README file before submitting my application.
- [ ✓ ] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [ ✓ ] I've checked the issue list before deciding what to submit.
- [ ✓ ] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ ✓ ] I've add work in proper folder
- [ ✓ ] I've not delete/modify previous codes.
> Added a new book for coding interviews!

- 5]. Important Books and Resources/Important_resources.md
Have added a useful resource about how to learn programming languages from the scaler topics in the reference section.
- []()
> Added a useful resource

- 6]. Behavioural Interview/behavioural-interview-ques.md
Added answers to some unanswered behavioral questions
-  YES
- Issue: some of behavioral questions were unanswered
- 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔
- Updated behavioral-interview-ques.md by answering some unanswered questions
-  I've read the instructions on the README file before submitting my application.
-  I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
-  I've checked the issue list before deciding what to submit.
-  I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
-  I've add work in proper folder
-  I've not delete/modify previous codes.
> Updated behavioral-interview-ques.md

- 4]. Projects/Data Science/Python/Deep Learning Projects/Natural Language Processing/New_Summarization/Readme.md
- 4]. Projects/Data Science/Python/Deep Learning Projects/Natural Language Processing/New_Summarization/main.py
> new Project news summarization using NLP

- 1]. DSA + CP/1]. DSA/1]. Data Structures/04]. Strings/C++/_01)_Longest-Common-prefix.cpp
- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/C++/_10)_Delete-Node-in-a-BST.cpp
- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/C++/_11)_Insert-in-BST.cpp
- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/C++/_12)_LCA-of-a-BST.cpp
- 1]. DSA + CP/1]. DSA/1]. Data Structures/13]. Binary Search Tree/C++/_13)_Search-in-BST.cpp
> Update repo By Shubhanshu

- 1]. DSA + CP/1]. DSA/1]. Data Structures/14]. Heap/Java/Heap.java
- [ ✅ ] YES
- []()
- [ ✅ ] 𝑫𝑺𝑨 + CP
- 
- [ ✅ ] I've read the instructions on the README file before submitting my application.
- [✅ ] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [✅ ] I've checked the issue list before deciding what to submit.
- [✅ ] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [ ✅] I've add work in proper folder
- [ ✅] I've not delete/modify previous codes.
> Created Heap.java

- 6]. Behavioural Interview/behavioural-interview-ques.md
- Spelling mistake Softare to software
> Update spelling error

- .github/PULL_REQUEST_TEMPLATE.md
- Issue Number: #426 
- Corrected typos in pull request template
> chore: correct typos in pull request template

- 1]. DSA + CP/1]. DSA/1]. Data Structures/04]. Strings/Java/Anagram.java
- []()
- (Add Running Work Demo Image)
> Added Anagram.java program in Strings section
